version: 2
updates:
- package-ecosystem: npm
  directory: "/jwt-react"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - Andrew-Chen-Wang
  labels:
  - update
- package-ecosystem: pip
  directory: "/server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - update
